# ## Documentation
# https://mosquitto.org/man/mosquitto-conf-5.html
# https://github.com/eclipse-mosquitto/mosquitto/blob/master/mosquitto.conf

allow_anonymous false

listener 1883
protocol mqtt
allow_anonymous true
accept_protocol_versions 3,4,5

listener 9001
protocol websockets
allow_anonymous true
accept_protocol_versions 5

# listener 9883
# protocol http_api
# allow_anonymous true
# accept_protocol_versions 5
# http_dir /usr/share/mosquitto/dashboard

persistence true
persistence_file mosquitto.db
persistence_location /mosquitto/data
