name: ${APP_NAME_HOST}

networks:
  internal:
    name: ${APP_NAME_HOST}_internal
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16

volumes:
  # nginx-proxy-manager:
  # letsencrypt:
  traefik-certs:
  tailscale:
  mosquitto-config:
  mosquitto-data:
  mosquitto-logs:
  grafana-data:
  authelia-secrets:
  authelia-data:
  lldap-data:
  influxdb-data:
  influxdb-plugins:
  dbgate-data:


secrets:
  TS_AUTHKEY:
    file: ${SECRETS_DIR}/TS_AUTHKEY
  PORKBUN_API_KEY:
    file: ${SECRETS_DIR}/PORKBUN_API_KEY
  PORKBUN_API_SECRET_KEY:
    file: ${SECRETS_DIR}/PORKBUN_API_SECRET_KEY
  AUTHELIA_OIDC_HMAC_SECRET:
    file: ${SECRETS_DIR}/AUTHELIA_OIDC_HMAC_SECRET
  AUTHELIA_OIDC_JWKS_KEY_PRIVATE:
    file: ${SECRETS_DIR}/AUTHELIA_OIDC_JWKS_KEY_PRIVATE
  GRAFANA_OAUTH_CLIENT_ID:
    file: ${SECRETS_DIR}/GRAFANA_OAUTH_CLIENT_ID
  GRAFANA_OAUTH_CLIENT_SECRET:
    file: ${SECRETS_DIR}/GRAFANA_OAUTH_CLIENT_SECRET
  GRAFANA_OAUTH_CLIENT_SECRET_HASHED_PBKDF2:
    file: ${SECRETS_DIR}/GRAFANA_OAUTH_CLIENT_SECRET_HASHED_PBKDF2
  LLDAP_JWT_SECRET:
    file: ${SECRETS_DIR}/LLDAP_JWT_SECRET
  LLDAP_KEY_SEED:
    file: ${SECRETS_DIR}/LLDAP_KEY_SEED
  LLDAP_ADMIN_PASSWORD:
    file: ${SECRETS_DIR}/LLDAP_ADMIN_PASSWORD
  INFLUXDB_ADMIN_TOKEN_JSON:
    file: ${SECRETS_DIR}/INFLUXDB_ADMIN_TOKEN_JSON
  INFLUXDB_ADMIN_TOKEN:
    file: ${SECRETS_DIR}/INFLUXDB_ADMIN_TOKEN

services:

  #   nginx-proxy-manager:
  #     image: docker.io/jc21/nginx-proxy-manager:latest
  #     pull_policy: always
  #     container_name: ${APP_NAME_HOST}_nginx-proxy-manager
  #     restart: always
  #     expose:
  #       - "80"
  #       - "81"
  #       - "443"
  #     env_file:
  #       - ./.env
  #       - path: ${ENV_DIR}/.env
  #         required: false
  #       - path: ${ENV_DIR}/nginx-proxy-manager.env
  #         required: false
  #     environment:
  #       INITIAL_ADMIN_EMAIL: "root@localhost.com"
  #       INITIAL_ADMIN_PASSWORD: "rootroot"
  #     volumes:
  #       - nginx-proxy-manager:/data
  #       - letsencrypt:/etc/letsencrypt
  #     networks:
  #       internal:
  #         ipv4_address: '172.18.0.2'
  #     healthcheck:
  #       test: ["CMD", "curl", "-f", "http://localhost:81"]
  #       interval: 10s
  #       timeout: 5s
  #       retries: 5
  #       start_period: 15s

  traefik:
    build:
      context: ./traefik
    pull_policy: always
    container_name: ${APP_NAME_HOST}_traefik
    restart: always
    expose:
      - "80"
      - "443"
      - "8080"
    env_file:
      - ./.env
      - path: ${ENV_DIR}/.env
        required: false
      - path: ${ENV_DIR}/traefik.env
        required: false
    secrets:
      - PORKBUN_API_KEY
      - PORKBUN_API_SECRET_KEY
    volumes:
      - ./traefik/config:/etc/traefik
      - traefik-certs:/etc/traefik-certs
    networks:
      internal:
        ipv4_address: '172.18.0.2'
    healthcheck:
      test: [ "CMD", "traefik", "healthcheck", "--ping" ]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 15s
    depends_on:
      authelia:
        condition: service_healthy

  tailscale:
    build:
      context: ./tailscale
    pull_policy: always
    container_name: ${APP_NAME_HOST}_tailscale
    restart: always
    env_file:
      - ./.env
      - path: ${ENV_DIR}/.env
        required: false
      - path: ${ENV_DIR}/tailscale.env
        required: false
    environment:
      TS_STATE_DIR: "/var/lib/tailscale"
      TS_USERSPACE: "true"
      TS_HOSTNAME: "${APP_NAME_HOST}"
      TS_ACCEPT_DNS: "false"
      TS_SERVE_CONFIG: "/config/serve-config.json"
      TS_ENABLE_HEALTH_CHECK: "true"
      TS_LOCAL_ADDR_PORT: "127.0.0.1:41234"
      TS_AUTH_ONCE: "true"
      TS_AUTHKEY_FILE: /run/secrets/TS_AUTHKEY
    secrets:
      - TS_AUTHKEY
    volumes:
      - tailscale:/var/lib/tailscale
      - ./tailscale/config:/config
    networks:
      internal:
        ipv4_address: '172.18.0.3'
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://127.0.0.1:41234/healthz" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    depends_on:
      traefik:
        condition: service_healthy

  mosquitto:
    image: eclipse-mosquitto:latest
    pull_policy: always
    container_name: ${APP_NAME_HOST}_mosquitto
    restart: always
    expose:
      - "1883"
      - "9001"
    env_file:
      - ./.env
      - path: ${ENV_DIR}/.env
        required: false
      - path: ${ENV_DIR}/mosquitto.env
        required: false
    volumes:
      - ./mosquitto/config:/mosquitto/config:ro
      - mosquitto-data:/mosquitto/data
      - mosquitto-logs:/mosquitto/log
    networks:
      internal:
        ipv4_address: '172.18.0.4'
    healthcheck:
      test: [ "CMD", "mosquitto_sub", "-V", "5", "-t", "$$SYS/#", "-C", "1", "-i", "healthcheck", "-W", "3" ] # Source: https://github.com/eclipse-mosquitto/mosquitto/issues/1270#issuecomment-1476038461
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s

  mqttx:
    image: emqx/mqttx-web:latest
    pull_policy: always
    container_name: ${APP_NAME_HOST}_mqttx
    restart: always
    expose:
      - "80"
    env_file:
      - ./.env
      - path: ${ENV_DIR}/.env
        required: false
      - path: ${ENV_DIR}/mqttx.env
        required: false
    networks:
      internal:
        ipv4_address: '172.18.0.5'
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://127.0.0.1:80" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  hardware-controller:
    build:
      context: ./hardware-controller
    pull_policy: always
    container_name: ${APP_NAME_HOST}_hardware-controller
    restart: always
    env_file:
      - ./.env
      - path: ${ENV_DIR}/.env
        required: false
      - path: ${ENV_DIR}/hardware-controller.env
        required: false
    environment:
      MQTT_HOST: "${APP_NAME_HOST}_mosquitto"
    volumes:
      - "/sys/firmware/devicetree/base:/sys/firmware/devicetree/base:ro"
      - "/proc/cpuinfo:/proc/cpuinfo:ro"
    devices:
      - "/dev/gpiomem:/dev/gpiomem"
      - "/dev/gpiochip0:/dev/gpiochip0"
      - "/dev/gpiochip1:/dev/gpiochip1"
    security_opt:
      - "systempaths=unconfined"
    networks:
      internal:
        ipv4_address: '172.18.0.6'
    # healthcheck:
    #   test: [ "CMD", "wget", "--spider", "-q", "http://127.0.0.1:80" ]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5
    #   start_period: 5s
    depends_on:
      mosquitto:
        condition: service_healthy

  grafana:
    image: grafana/grafana:latest
    pull_policy: always
    container_name: ${APP_NAME_HOST}_grafana
    restart: always
    expose:
      - "3000"
    user: "root"
    env_file:
      - ./.env
      - path: ${ENV_DIR}/.env
        required: false
      - path: ${ENV_DIR}/grafana.env
        required: false
    environment:
      GF_SERVER_ROOT_URL: "https://grafana.${APP_HOST}"
      GF_SECURITY_DISABLE_INITIAL_ADMIN_CREATION: "true"
      GF_SECURITY_COOKIE_SECURE: "true"
      GF_SECURITY_COOKIE_SAMESITE: "lax"
      GF_SECURITY_ALLOW_EMBEDDING: "true"
      GF_AUTH_GENERIC_OAUTH_ENABLED: "true"
      GF_AUTH_GENERIC_OAUTH_NAME: "Authelia"
      GF_AUTH_GENERIC_OAUTH_ICON: "signin"
      GF_AUTH_GENERIC_OAUTH_CLIENT_ID__FILE: "/run/secrets/GRAFANA_OAUTH_CLIENT_ID"
      GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET__FILE: "/run/secrets/GRAFANA_OAUTH_CLIENT_SECRET"
      GF_AUTH_GENERIC_OAUTH_SCOPES: "openid profile email groups"
      GF_AUTH_GENERIC_OAUTH_EMPTY_SCOPES: "false"
      GF_AUTH_GENERIC_OAUTH_AUTH_URL: "https://authelia.${APP_HOST}/api/oidc/authorization"
      GF_AUTH_GENERIC_OAUTH_TOKEN_URL: "https://authelia.${APP_HOST}/api/oidc/token"
      GF_AUTH_GENERIC_OAUTH_API_URL: "https://authelia.${APP_HOST}/api/oidc/userinfo"
      GF_AUTH_GENERIC_OAUTH_LOGIN_ATTRIBUTE_PATH: ""
      GF_AUTH_GENERIC_OAUTH_GROUPS_ATTRIBUTE_PATH: "groups"
      GF_AUTH_GENERIC_OAUTH_NAME_ATTRIBUTE_PATH: "name"
      GF_AUTH_GENERIC_OAUTH_USE_PKCE: "true"
      GF_AUTH_GENERIC_OAUTH_ROLE_ATTRIBUTE_PATH: "contains(groups[*], 'admins') && 'GrafanaAdmin' || contains(groups[*], 'grafana_admins') && 'Admin' || contains(groups[*], 'grafana_editors') && 'Editor' || 'Viewer'"
      GF_AUTH_GENERIC_OAUTH_AUTH_STYLE: "InHeader"
      GF_AUTH_GENERIC_OAUTH_ALLOW_SIGN_UP: "true"
      GF_AUTH_GENERIC_OAUTH_AUTO_LOGIN: "true"
      GF_AUTH_GENERIC_OAUTH_ALLOW_ASSIGN_GRAFANA_ADMIN: "true"
      GF_AUTH_GENERIC_OAUTH_SIGNOUT_REDIRECT_URL: "https://authelia.${APP_HOST}/logout?rd=https%3A%2F%2Fgrafana.${APP_HOST}%2F"
      GF_PROVISIONING_INFLUXDB_TOKEN__FILE: "/run/secrets/INFLUXDB_ADMIN_TOKEN"
      GF_NEWS_NEWS_FEED_ENABLED: "false"
    secrets:
      - GRAFANA_OAUTH_CLIENT_ID
      - GRAFANA_OAUTH_CLIENT_SECRET
      - INFLUXDB_ADMIN_TOKEN
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
    networks:
      internal:
        ipv4_address: '172.18.0.7'
    extra_hosts:
      - "grafana.com:0.0.0.0"
      - "stats.grafana.com:0.0.0.0"
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://127.0.0.1:3000/api/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  authelia:
    build:
      context: ./authelia
    pull_policy: always
    container_name: ${APP_NAME_HOST}_authelia
    restart: always
    expose:
      - "9091"
    env_file:
      - ./.env
      - path: ${ENV_DIR}/.env
        required: false
      - path: ${ENV_DIR}/authelia.env
        required: false
    environment:
      AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET_FILE: "/secrets/jwt"
      AUTHELIA_SESSION_SECRET_FILE: "/secrets/session"
      AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE: "/secrets/storage_key"
      X_AUTHELIA_CONFIG_FILTERS: "template"
      X_AUTHELIA_HEALTHCHECK: "true"
      # LLDAP_LDAP_BASE_DN: "//** Generated from APP_HOST in entrypoint-hook.sh **//"
    secrets:
      - AUTHELIA_OIDC_HMAC_SECRET
      - AUTHELIA_OIDC_JWKS_KEY_PRIVATE
      - GRAFANA_OAUTH_CLIENT_ID
      - GRAFANA_OAUTH_CLIENT_SECRET_HASHED_PBKDF2
      - LLDAP_ADMIN_PASSWORD
    volumes:
      - ./authelia/config:/config:ro
      - authelia-secrets:/secrets
      - authelia-data:/data
    networks:
      internal:
        ipv4_address: '172.18.0.8'
    healthcheck:
      test: [ "CMD", "./healthcheck.sh" ]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s
    depends_on:
      lldap:
        condition: service_healthy

  lldap:
    build:
      context: ./lldap
    pull_policy: always
    container_name: ${APP_NAME_HOST}_lldap
    restart: always
    expose:
      - "3890"
      - "17170"
    env_file:
      - ./.env
      - path: ${ENV_DIR}/.env
        required: false
      - path: ${ENV_DIR}/lldap.env
        required: false
    environment:
      UID: "0"
      GID: "0"
      TZ: "${TIMEZONE}"
      LLDAP_JWT_SECRET_FILE: "/run/secrets/LLDAP_JWT_SECRET"
      LLDAP_KEY_SEED: "/run/secrets/LLDAP_KEY_SEED"
      LLDAP_KEY_FILE: ""
      LLDAP_LDAP_USER_DN: "admin"
      LLDAP_LDAP_USER_EMAIL: "admin@${APP_HOST}"
      LLDAP_LDAP_USER_PASS_FILE: "/run/secrets/LLDAP_ADMIN_PASSWORD"
      LLDAP_FORCE_LDAP_USER_PASS_RESET: "always"
      # LLDAP_LDAP_BASE_DN: "//** Generated from APP_HOST in entrypoint-hook.sh **//"
    secrets:
      - LLDAP_JWT_SECRET
      - LLDAP_KEY_SEED
      - LLDAP_ADMIN_PASSWORD
    volumes:
      - lldap-data:/data
      - ./lldap/bootstrap:/bootstrap:ro
    networks:
      internal:
        ipv4_address: '172.18.0.9'
    healthcheck:
      test: [ "CMD", "/app/lldap", "healthcheck", "--config-file", "/data/lldap_config.toml" ]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s

  influxdb:
    image: influxdb:3-core
    # build:
    #   context: ./influxdb
    pull_policy: always
    container_name: ${APP_NAME_HOST}_influxdb
    restart: always
    expose:
      - "8181"
    user: "root"
    env_file:
      - ./.env
      - path: ${ENV_DIR}/.env
        required: false
      - path: ${ENV_DIR}/influxdb.env
        required: false
    environment:
      # https://docs.influxdata.com/influxdb3/core/reference/config-options/
      INFLUXDB3_NODE_IDENTIFIER_PREFIX: "node0"
      INFLUXDB3_OBJECT_STORE: "file"
      INFLUXDB3_DB_DIR: "/var/lib/influxdb3/data"
      INFLUXDB3_PLUGIN_DIR: "/var/lib/influxdb3/plugins"
      INFLUXDB3_PROVISIONING_DIR: "/var/lib/influxdb3/provisioning"
      INFLUXDB3_LOG_FILTER: "info"
      INFLUXDB3_NUM_IO_THREADS: "2"
      INFLUXDB3_NUM_DATAFUSION_THREADS: "2"
      INFLUXDB3_ADMIN_TOKEN_FILE: "/run/secrets/INFLUXDB_ADMIN_TOKEN_JSON" # [ ! -d "./influxdb3-admin-token" ] && mkdir -p ./influxdb3-admin-token && { docker run --user "$(id -u):$(id -g)" --rm -v "./influxdb3-admin-token:/admin-token" influxdb:3-core influxdb3 create token --admin --name "admin-token" --offline --output-file /admin-token/admin-token.json >/dev/null; [ ! -f "./influxdb3-admin-token/admin-token.json" ] || cat "./influxdb3-admin-token/admin-token.json"; } && rm -rf ./influxdb3-admin-token
      INFLUXDB3_DISABLE_AUTHZ: "health"
    secrets:
      - INFLUXDB_ADMIN_TOKEN_JSON
      - INFLUXDB_ADMIN_TOKEN
    volumes:
      - influxdb-data:/var/lib/influxdb3/data
      - influxdb-plugins:/var/lib/influxdb3/plugins
      - ./influxdb/provisioning:/var/lib/influxdb3/provisioning
    networks:
      internal:
        ipv4_address: '172.18.0.10'
    healthcheck:
      test: [ "CMD", "curl", "-sfo", "/dev/null", "http://127.0.0.1:8181/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  telegraf:
    build:
      context: ./telegraf
    pull_policy: always
    container_name: ${APP_NAME_HOST}_telegraf
    restart: always
    user: "root"
    env_file:
      - ./.env
      - path: ${ENV_DIR}/.env
        required: false
      - path: ${ENV_DIR}/telegraf.env
        required: false
    environment:
      # HOST_ETC: '/hostfs/etc'
      HOST_PROC: '/hostfs/proc'
      HOST_SYS: '/hostfs/sys'
      # HOST_VAR: '/hostfs/var'
      HOST_RUN: '/hostfs/run'
      HOST_MOUNT_PREFIX: '/hostfs'
    secrets:
      - INFLUXDB_ADMIN_TOKEN
    volumes:
      - ./telegraf/config/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      # - /etc:/hostfs/etc:ro
      - /proc:/hostfs/proc:ro
      - /sys:/hostfs/sys:ro
      # - /var:/hostfs/var:ro
      # - /run:/hostfs/run:ro
      - /run/udev:/hostfs/run/udev:ro
      - /dev:/hostfs/dev:ro
      # - /etc/os-release:/etc/os-release:ro
    networks:
      internal:
        ipv4_address: '172.18.0.11'
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://127.0.0.1:8080/health" ]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 15s
    depends_on:
      mosquitto:
        condition: service_healthy
      influxdb:
        condition: service_healthy
      socket-proxy:
        condition: service_healthy

  socket-proxy:
    image: ghcr.io/tecnativa/docker-socket-proxy:master
    pull_policy: always
    container_name: ${APP_NAME_HOST}_socket-proxy
    restart: always
    user: "root"
    env_file:
      - ./.env
      - path: ${ENV_DIR}/.env
        required: false
      - path: ${ENV_DIR}/socket-proxy.env
        required: false
    environment:
      CONTAINERS: "1"
      INFO: "1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      internal:
        ipv4_address: '172.18.0.12'
    healthcheck:
      test: [ "CMD", "nc", "-z", "127.0.0.1", "2375" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 15s

  glance:
    image: glanceapp/glance:latest
    pull_policy: always
    container_name: ${APP_NAME_HOST}_glance
    restart: always
    expose:
      - "8080"
    env_file:
      - ./.env
      - path: ${ENV_DIR}/.env
        required: false
      - path: ${ENV_DIR}/glance.env
        required: false
    volumes:
      - ./glance/config:/app/config
      - ./glance/assets:/app/assets
    networks:
      internal:
        ipv4_address: '172.18.0.13'
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://127.0.0.1:8080/api/healthz" ]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s

  mediamtx:
    image: bluenviron/mediamtx:latest-ffmpeg
    pull_policy: always
    container_name: ${APP_NAME_HOST}_mediamtx
    restart: always
    expose:
      - '8554' # RTSP
      - '1935' # RTMP
      - '8888' # HLS
      - '8889' # WebRTC
      - '8189/udp' # WebRTC local UDP
      - '8890/udp' # SRT
      - '9997' # API
    env_file:
      - ./.env
      - path: ${ENV_DIR}/.env
        required: false
      - path: ${ENV_DIR}/mediamtx.env
        required: false
    environment:
      MTX_RTSPTRANSPORTS: 'tcp'
      MTX_WEBRTCADDITIONALHOSTS: 'mediamtx-webrtc.${APP_HOST}'
    volumes:
      - ./mediamtx/config/mediamtx.yml:/mediamtx.yml
      - /dev:/dev
      - /run/udev:/run/udev:ro
    device_cgroup_rules:
      - 'c 81:* rmw'
    networks:
      internal:
        ipv4_address: '172.18.0.14'
    healthcheck:
      test: [ "CMD", "wget", "-q", "-o", "/dev/null", "http://127.0.0.1:9997/v3/info" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
