name: ${APP_NAME_HOST}

networks:
  internal:
    name: ${APP_NAME_HOST}_internal
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16

volumes:
  # nginx-proxy-manager:
  # letsencrypt:
  traefik-certs:
  tailscale:
  mosquitto-config:
  mosquitto-data:
  mosquitto-logs:
  grafana-data:
  authelia-secrets:
  authelia-data:
  lldap_data:


secrets:
  TS_AUTHKEY:
    file: ${SECRETS_DIR}/TS_AUTHKEY
  PORKBUN_API_KEY:
    file: ${SECRETS_DIR}/PORKBUN_API_KEY
  PORKBUN_API_SECRET_KEY:
    file: ${SECRETS_DIR}/PORKBUN_API_SECRET_KEY
  AUTHELIA_OIDC_HMAC_SECRET:
    file: ${SECRETS_DIR}/AUTHELIA_OIDC_HMAC_SECRET
  AUTHELIA_OIDC_JWKS_KEY_PRIVATE:
    file: ${SECRETS_DIR}/AUTHELIA_OIDC_JWKS_KEY_PRIVATE
  GRAFANA_OAUTH_CLIENT_ID:
    file: ${SECRETS_DIR}/GRAFANA_OAUTH_CLIENT_ID
  GRAFANA_OAUTH_CLIENT_SECRET:
    file: ${SECRETS_DIR}/GRAFANA_OAUTH_CLIENT_SECRET
  GRAFANA_OAUTH_CLIENT_SECRET_HASHED_PBKDF2:
    file: ${SECRETS_DIR}/GRAFANA_OAUTH_CLIENT_SECRET_HASHED_PBKDF2
  LLDAP_JWT_SECRET:
    file: ${SECRETS_DIR}/LLDAP_JWT_SECRET
  LLDAP_KEY_SEED:
    file: ${SECRETS_DIR}/LLDAP_KEY_SEED
  LLDAP_ADMIN_PASSWORD:
    file: ${SECRETS_DIR}/LLDAP_ADMIN_PASSWORD

services:

  #   nginx-proxy-manager:
  #     image: docker.io/jc21/nginx-proxy-manager:latest
  #     pull_policy: always
  #     container_name: ${APP_NAME_HOST}_nginx-proxy-manager
  #     restart: always
  #     expose:
  #       - "80"
  #       - "81"
  #       - "443"
  #     env_file:
  #       - ./.env
  #       - path: ${ENV_DIR}/.env
  #         required: false
  #       - path: ${ENV_DIR}/nginx-proxy-manager.env
  #         required: false
  #     environment:
  #       INITIAL_ADMIN_EMAIL: "root@localhost.com"
  #       INITIAL_ADMIN_PASSWORD: "rootroot"
  #     volumes:
  #       - nginx-proxy-manager:/data
  #       - letsencrypt:/etc/letsencrypt
  #     networks:
  #       internal:
  #         ipv4_address: '172.18.0.2'
  #     healthcheck:
  #       test: ["CMD", "curl", "-f", "http://localhost:81"]
  #       interval: 10s
  #       timeout: 5s
  #       retries: 5
  #       start_period: 15s

  traefik:
    build:
      context: ./traefik
    pull_policy: always
    container_name: ${APP_NAME_HOST}_traefik
    restart: always
    expose:
      - "80"
      - "443"
    env_file:
      - ./.env
      - path: ${ENV_DIR}/.env
        required: false
      - path: ${ENV_DIR}/traefik.env
        required: false
    secrets:
      - PORKBUN_API_KEY
      - PORKBUN_API_SECRET_KEY
    volumes:
      - ./traefik/config:/etc/traefik
      - traefik-certs:/etc/traefik-certs
    networks:
      internal:
        ipv4_address: '172.18.0.2'
    healthcheck:
      test: [ "CMD", "traefik", "healthcheck", "--ping" ]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 15s
    depends_on:
      authelia:
        condition: service_healthy

  tailscale:
    build:
      context: ./tailscale
    pull_policy: always
    container_name: ${APP_NAME_HOST}_tailscale
    restart: always
    env_file:
      - ./.env
      - path: ${ENV_DIR}/.env
        required: false
      - path: ${ENV_DIR}/tailscale.env
        required: false
    environment:
      TS_STATE_DIR: "/var/lib/tailscale"
      TS_USERSPACE: "true"
      TS_HOSTNAME: "${APP_NAME_HOST}"
      TS_ACCEPT_DNS: "false"
      TS_SERVE_CONFIG: "/config/serve-config.json"
      TS_ENABLE_HEALTH_CHECK: "true"
      TS_LOCAL_ADDR_PORT: "127.0.0.1:41234"
      TS_AUTH_ONCE: "true"
      TS_AUTHKEY_FILE: /run/secrets/TS_AUTHKEY
    secrets:
      - TS_AUTHKEY
    volumes:
      - tailscale:/var/lib/tailscale
      - ./tailscale/config:/config
    networks:
      internal:
        ipv4_address: '172.18.0.3'
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://127.0.0.1:41234/healthz" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    depends_on:
      traefik:
        condition: service_healthy

  mosquitto:
    image: eclipse-mosquitto:latest
    pull_policy: always
    container_name: ${APP_NAME_HOST}_mosquitto
    restart: always
    expose:
      - "1883"
      - "9001"
    env_file:
      - ./.env
      - path: ${ENV_DIR}/.env
        required: false
      - path: ${ENV_DIR}/mosquitto.env
        required: false
    volumes:
      - ./mosquitto/config:/mosquitto/config:ro
      - mosquitto-data:/mosquitto/data
      - mosquitto-logs:/mosquitto/log
    networks:
      internal:
        ipv4_address: '172.18.0.4'
    healthcheck:
      test: [ "CMD", "mosquitto_sub", "-V", "5", "-t", "$$SYS/#", "-C", "1", "-i", "healthcheck", "-W", "3" ] # Source: https://github.com/eclipse-mosquitto/mosquitto/issues/1270#issuecomment-1476038461
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s

  mqttx:
    image: emqx/mqttx-web:latest
    pull_policy: always
    container_name: ${APP_NAME_HOST}_mqttx
    restart: always
    expose:
      - "80"
    env_file:
      - ./.env
      - path: ${ENV_DIR}/.env
        required: false
      - path: ${ENV_DIR}/mqttx.env
        required: false
    networks:
      internal:
        ipv4_address: '172.18.0.5'
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://127.0.0.1:80" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  hardware-controller:
    build:
      context: ./hardware-controller
    pull_policy: always
    container_name: ${APP_NAME_HOST}_hardware-controller
    restart: always
    env_file:
      - ./.env
      - path: ${ENV_DIR}/.env
        required: false
      - path: ${ENV_DIR}/hardware-controller.env
        required: false
    environment:
      MQTT_HOST: "${APP_NAME_HOST}_mosquitto"
    volumes:
      - "/sys/firmware/devicetree/base:/sys/firmware/devicetree/base:ro"
      - "/proc/cpuinfo:/proc/cpuinfo:ro"
    devices:
      - "/dev/gpiomem:/dev/gpiomem"
      - "/dev/gpiochip0:/dev/gpiochip0"
      - "/dev/gpiochip1:/dev/gpiochip1"
    security_opt:
      - "systempaths=unconfined"
    networks:
      internal:
        ipv4_address: '172.18.0.6'
    # healthcheck:
    #   test: [ "CMD", "wget", "--spider", "-q", "http://127.0.0.1:80" ]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5
    #   start_period: 5s
    depends_on:
      mosquitto:
        condition: service_healthy

  grafana:
    image: grafana/grafana:latest
    pull_policy: always
    container_name: ${APP_NAME_HOST}_grafana
    restart: always
    expose:
      - "3000"
    user: "root"
    env_file:
      - ./.env
      - path: ${ENV_DIR}/.env
        required: false
      - path: ${ENV_DIR}/grafana.env
        required: false
    environment:
      GF_SERVER_ROOT_URL: "https://grafana.${APP_HOST}"
      GF_SECURITY_DISABLE_INITIAL_ADMIN_CREATION: "true"
      GF_AUTH_GENERIC_OAUTH_ENABLED: "true"
      GF_AUTH_GENERIC_OAUTH_NAME: "Authelia"
      GF_AUTH_GENERIC_OAUTH_ICON: "signin"
      GF_AUTH_GENERIC_OAUTH_CLIENT_ID__FILE: "/run/secrets/GRAFANA_OAUTH_CLIENT_ID"
      GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET__FILE: "/run/secrets/GRAFANA_OAUTH_CLIENT_SECRET"
      GF_AUTH_GENERIC_OAUTH_SCOPES: "openid profile email groups"
      GF_AUTH_GENERIC_OAUTH_EMPTY_SCOPES: "false"
      GF_AUTH_GENERIC_OAUTH_AUTH_URL: "https://authelia.${APP_HOST}/api/oidc/authorization"
      GF_AUTH_GENERIC_OAUTH_TOKEN_URL: "https://authelia.${APP_HOST}/api/oidc/token"
      GF_AUTH_GENERIC_OAUTH_API_URL: "https://authelia.${APP_HOST}/api/oidc/userinfo"
      GF_AUTH_GENERIC_OAUTH_LOGIN_ATTRIBUTE_PATH: ""
      GF_AUTH_GENERIC_OAUTH_GROUPS_ATTRIBUTE_PATH: "groups"
      GF_AUTH_GENERIC_OAUTH_NAME_ATTRIBUTE_PATH: "name"
      GF_AUTH_GENERIC_OAUTH_USE_PKCE: "true"
      GF_AUTH_GENERIC_OAUTH_ROLE_ATTRIBUTE_PATH: "contains(groups[*], 'admins') && 'GrafanaAdmin' || contains(groups[*], 'grafana_admins') && 'Admin' || contains(groups[*], 'grafana_editors') && 'Editor' || 'Viewer'"
      GF_AUTH_GENERIC_OAUTH_AUTH_STYLE: "InHeader"
      GF_AUTH_GENERIC_OAUTH_ALLOW_SIGN_UP: "true"
      GF_AUTH_GENERIC_OAUTH_AUTO_LOGIN: "true"
      GF_AUTH_GENERIC_OAUTH_ALLOW_ASSIGN_GRAFANA_ADMIN: "true"
      GF_AUTH_GENERIC_OAUTH_SIGNOUT_REDIRECT_URL: "https://authelia.${APP_HOST}/logout"
    secrets:
      - GRAFANA_OAUTH_CLIENT_ID
      - GRAFANA_OAUTH_CLIENT_SECRET
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      internal:
        ipv4_address: '172.18.0.7'
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://127.0.0.1:3000/api/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  authelia:
    build:
      context: ./authelia
    pull_policy: always
    container_name: ${APP_NAME_HOST}_authelia
    restart: always
    expose:
      - "9091"
    env_file:
      - ./.env
      - path: ${ENV_DIR}/.env
        required: false
      - path: ${ENV_DIR}/authelia.env
        required: false
    environment:
      AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET_FILE: "/secrets/jwt"
      AUTHELIA_SESSION_SECRET_FILE: "/secrets/session"
      AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE: "/secrets/storage_key"
      X_AUTHELIA_CONFIG_FILTERS: "template"
      X_AUTHELIA_HEALTHCHECK: "true"
      # LLDAP_LDAP_BASE_DN: "//** Generated from APP_HOST in entrypoint-hook.sh **//"
    secrets:
      - AUTHELIA_OIDC_HMAC_SECRET
      - AUTHELIA_OIDC_JWKS_KEY_PRIVATE
      - GRAFANA_OAUTH_CLIENT_ID
      - GRAFANA_OAUTH_CLIENT_SECRET_HASHED_PBKDF2
      - LLDAP_ADMIN_PASSWORD
    volumes:
      - ./authelia/config:/config:ro
      - authelia-secrets:/secrets
      - authelia-data:/data
    networks:
      internal:
        ipv4_address: '172.18.0.8'
    healthcheck:
      test: [ "CMD", "./healthcheck.sh" ]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s
    depends_on:
      lldap:
        condition: service_healthy

  lldap:
    build:
      context: ./lldap
    pull_policy: always
    container_name: ${APP_NAME_HOST}_lldap
    restart: always
    expose:
      - "3890"
      - "17170"
    env_file:
      - ./.env
      - path: ${ENV_DIR}/.env
        required: false
      - path: ${ENV_DIR}/lldap.env
        required: false
    environment:
      UID: "0"
      GID: "0"
      TZ: "${TIMEZONE}"
      LLDAP_JWT_SECRET_FILE: "/run/secrets/LLDAP_JWT_SECRET"
      LLDAP_KEY_SEED: "/run/secrets/LLDAP_KEY_SEED"
      LLDAP_KEY_FILE: ""
      LLDAP_LDAP_USER_DN: "admin"
      LLDAP_LDAP_USER_EMAIL: "admin@${APP_HOST}"
      LLDAP_LDAP_USER_PASS_FILE: "/run/secrets/LLDAP_ADMIN_PASSWORD"
      LLDAP_FORCE_LDAP_USER_PASS_RESET: "always"
      # LLDAP_LDAP_BASE_DN: "//** Generated from APP_HOST in entrypoint-hook.sh **//"
    secrets:
      - LLDAP_JWT_SECRET
      - LLDAP_KEY_SEED
      - LLDAP_ADMIN_PASSWORD
    volumes:
      - lldap_data:/data
    networks:
      internal:
        ipv4_address: '172.18.0.9'
    healthcheck:
      test: [ "CMD", "/app/lldap", "healthcheck", "--config-file", "/data/lldap_config.toml" ]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s
