# Documentation:
# https://doc.traefik.io/traefik/reference/routing-configuration/dynamic-configuration-methods/
# https://doc.traefik.io/traefik/reference/routing-configuration/http/tls/overview/

http:
  services:
    svc_glance-8080:
      loadBalancer:
        servers:
          - url: "http://{{ env "APP_NAME_HOST" }}_glance:8080"
  routers:
    glance-8080:
      rule: "Host(`{{ env "APP_HOST" }}`)"
      service: svc_glance-8080
      entryPoints: ["websecure"]
      middlewares:
        - "auth-proxy"
      tls:
        certResolver: porkbun-api
