# Documentation:
# https://doc.traefik.io/traefik/reference/routing-configuration/dynamic-configuration-methods/
# https://doc.traefik.io/traefik/reference/routing-configuration/http/tls/overview/

http:
  services:
    svc_moquitto-9001:
      loadBalancer:
        servers:
          - url: "http://{{ env "APP_NAME_HOST" }}_mosquitto:9001"
  routers:
    mosquitto-9001:
      rule: "Host(`mosquitto.{{ env "APP_HOST" }}`)"
      service: svc_moquitto-9001
      entryPoints: ["websecure"]
      tls:
        certResolver: porkbun-api

tcp:
  services:
    svc_mosquitto-1883:
      loadBalancer:
        servers:
          - address: "{{ env "APP_NAME_HOST" }}_mosquitto:1883"
  routers:
    mosquitto-1883:
      rule: "HostSNI(`mosquitto.{{ env "APP_HOST" }}`)"
      service: svc_mosquitto-1883
      entryPoints: ["websecure"]
      tls:
        passthrough: false
        certResolver: porkbun-api