# Documentation:
# https://doc.traefik.io/traefik/reference/routing-configuration/dynamic-configuration-methods/
# https://doc.traefik.io/traefik/reference/routing-configuration/http/tls/overview/

http:
  services:
    svc_mqttx-80:
      loadBalancer:
        servers:
          - url: "http://{{ env "APP_NAME_HOST" }}_mqttx:80"
  routers:
    mqttx-80:
      rule: "Host(`mqttx.{{ env "APP_HOST" }}`)"
      service: svc_mqttx-80
      entryPoints: ["websecure"]
      middlewares:
        - "auth-proxy"
      tls:
        certResolver: porkbun-api
