[[secretstores.docker]] # https://github.com/influxdata/telegraf/tree/master/plugins/secretstores/docker
  id = "docker_secrets"

[[outputs.health]] # https://docs.influxdata.com/telegraf/v1/output-plugins/health/
  service_address = "http://:8080"

[[outputs.influxdb_v3]] # https://docs.influxdata.com/telegraf/v1/output-plugins/influxdb_v3/
  urls = ["http://${APP_HOST}_influxdb:8181"]
  token = "@{docker_secrets:INFLUXDB_ADMIN_TOKEN}"
  database = "sensor-data"
  # database_tag = "__influx__database"
  # exclude_database_tag = true

[[inputs.mqtt_consumer]] # https://docs.influxdata.com/telegraf/v1/input-plugins/mqtt_consumer/
  servers = ["tcp://${APP_HOST}_mosquitto:1883"]
  # client_id = "telegraf"
  client_trace = true
  topics = [
    "v1/sensors/+/+/+",
  ]
  data_format = "value"
  data_type = "float"

  ## Optional: Extract tags from the topic structure
  ## This turns sensors/room1/temperature into a tag: location=room1
  [[inputs.mqtt_consumer.topic_parsing]]
    topic = "v1/sensors/+/+/+"
    measurement = "_/_/_/_/measurement"
    tags = "_/_/sensor-type/location/_"
    # fields = "_/_/_/_/_"