# ## General Settings

[agent] # https://docs.influxdata.com/telegraf/v1/configuration/#agent-configuration
  skip_processors_after_aggregators = true
  interval = "10s"
  collection_jitter = "1s"
  hostname = "${APP_NAME_HOST}"

[[secretstores.docker]] # https://github.com/influxdata/telegraf/tree/master/plugins/secretstores/docker
  id = "docker_secrets" # Query available secretstores with: docker run --rm -v ./telegraf/config/telegraf.conf:/etc/telegraf/telegraf.conf telegraf:latest telegraf plugins secretstores

# ## Outputs

[[outputs.health]] # https://docs.influxdata.com/telegraf/v1/output-plugins/health/
  service_address = "http://:8080"

[[outputs.influxdb_v3]] # https://docs.influxdata.com/telegraf/v1/output-plugins/influxdb_v3/
  urls = ["http://${APP_NAME_HOST}_influxdb:8181"]
  token = "@{docker_secrets:INFLUXDB_ADMIN_TOKEN}"
  database_tag = "__influxdb__database"
  exclude_database_tag = true

# ## Inputs

# # Host & Docker Metrics

[[inputs.cpu]] # https://docs.influxdata.com/telegraf/v1/input-plugins/cpu/
  percpu = true
  totalcpu = true
  collect_cpu_time = false
  report_active = false
  core_tags = true
  [inputs.cpu.tags]
    __influxdb__database = "metrics"

[[inputs.mem]] # https://docs.influxdata.com/telegraf/v1/input-plugins/mem/
  [inputs.mem.tags]
    __influxdb__database = "metrics"

[[inputs.disk]] # https://docs.influxdata.com/telegraf/v1/input-plugins/disk/
  ignore_fs = ["tmpfs", "devtmpfs", "devfs", "iso9660", "overlay", "aufs", "squashfs"]
  [inputs.disk.tags]
    __influxdb__database = "metrics"

[[inputs.diskio]] # https://docs.influxdata.com/telegraf/v1/input-plugins/diskio/
  [inputs.diskio.tags]
    __influxdb__database = "metrics"

[[inputs.net]] # https://docs.influxdata.com/telegraf/v1/input-plugins/net/
  interfaces = ["eth*", "enp*", "wlan*", "tailscale*"]
  [inputs.net.tags]
    __influxdb__database = "metrics"

[[inputs.docker]] # https://docs.influxdata.com/telegraf/v1/input-plugins/docker/
  endpoint = "tcp://${APP_NAME_HOST}_socket-proxy:2375"
  container_state_include = ["running"]
  timeout = "10s"
  total_include = ["cpu", "network", "blkio"]
  [inputs.docker.tags]
    __influxdb__database = "metrics"

# # Sensor Data

[[inputs.mqtt_consumer]] # https://docs.influxdata.com/telegraf/v1/input-plugins/mqtt_consumer/
  servers = ["tcp://${APP_NAME_HOST}_mosquitto:1883"]
  topics = [
    "v1/sensors/+/+/+", # Ex.: v1/sensors/dht22/inside/temperature
  ]
  data_format = "value"
  data_type = "float"
  [[inputs.mqtt_consumer.topic_parsing]]
    topic = "v1/sensors/+/+/+"
    measurement = "_/_/_/_/measurement"
    tags = "_/_/sensor-type/location/_"
    # fields = "_/_/_/_/_"
  [inputs.mqtt_consumer.tags]
    __influxdb__database = "sensor-data"