"""
This type stub file was generated by pyright.
"""

import typing
from typing import List, Optional, Sequence, Tuple, Union
from circuitpython_typing import ReadableBuffer

"""Support for multi-channel audio synthesis

At least 2 simultaneous notes are supported.  samd5x, mimxrt10xx and rp2040 platforms support up to 12 notes.
"""
class EnvelopeState:
    ATTACK: EnvelopeState
    DECAY: EnvelopeState
    SUSTAIN: EnvelopeState
    RELEASE: EnvelopeState
    ...


BlockInput = Union["Math", "LFO", float, None]
class Envelope:
    def __init__(self, *, attack_time: Optional[float] = ..., decay_time: Optional[float] = ..., release_time: Optional[float] = ..., attack_level: Optional[float] = ..., sustain_level: Optional[float] = ...) -> None:
        """Construct an Envelope object

        The Envelope defines an ADSR (Attack, Decay, Sustain, Release) envelope with linear amplitude ramping. A note starts at 0 volume, then increases to ``attack_level`` over ``attack_time`` seconds; then it decays to ``sustain_level`` over ``decay_time`` seconds. Finally, when the note is released, it decreases to ``0`` volume over ``release_time``.

        If the ``sustain_level`` of an envelope is 0, then the decay and sustain phases of the note are always omitted. The note is considered to be released as soon as the envelope reaches the end of the attack phase. The ``decay_time`` is ignored. This is similar to how a plucked or struck instrument behaves.

        If a note is released before it reaches its sustain phase, it decays with the same slope indicated by ``sustain_level/release_time`` (or ``attack_level/release_time`` for plucked envelopes)

        :param float attack_time: The time in seconds it takes to ramp from 0 volume to attack_volume
        :param float decay_time: The time in seconds it takes to ramp from attack_volume to sustain_volume
        :param float release_time: The time in seconds it takes to ramp from sustain_volume to release_volume. When a note is released before it has reached the sustain phase, the release is done with the same slope indicated by ``release_time`` and ``sustain_level``. If the ``sustain_level`` is ``0.0`` then the release slope calculations use the ``attack_level`` instead.
        :param float attack_level: The level, in the range ``0.0`` to ``1.0`` of the peak volume of the attack phase
        :param float sustain_level: The level, in the range ``0.0`` to ``1.0`` of the volume of the sustain phase relative to the attack level
        """
        ...
    
    attack_time: float
    decay_time: float
    release_time: float
    attack_level: float
    sustain_level: float


def from_file(file: typing.BinaryIO, *, sample_rate: int = ..., waveform: Optional[ReadableBuffer] = ..., envelope: Optional[Envelope] = ...) -> MidiTrack:
    """Create an AudioSample from an already opened MIDI file.
    Currently, only single-track MIDI (type 0) is supported.

    :param typing.BinaryIO file: Already opened MIDI file
    :param int sample_rate: The desired playback sample rate; higher sample rate requires more memory
    :param ReadableBuffer waveform: A single-cycle waveform. Default is a 50% duty cycle square wave. If specified, must be a ReadableBuffer of type 'h' (signed 16 bit)
    :param Envelope envelope: An object that defines the loudness of a note over time. The default envelope provides no ramping, voices turn instantly on and off.

    Playing a MIDI file from flash::

          import audioio
          import board
          import synthio

          data = open("single-track.midi", "rb")
          midi = synthio.from_file(data)
          a = audioio.AudioOut(board.A0)

          print("playing")
          a.play(midi)
          while a.playing:
            pass
          print("stopped")"""
    ...

def midi_to_hz(midi_note: float) -> float:
    """Converts the given midi note (60 = middle C, 69 = concert A) to Hz"""
    ...

def voct_to_hz(ctrl: float) -> float:
    """Converts a 1v/octave signal to Hz.

    24/12 (2.0) corresponds to middle C, 33/12 (2.75) is concert A."""
    ...

waveform_max_length: int
class FilterMode:
    """The type of filter"""
    LOW_PASS: FilterMode
    HIGH_PASS: FilterMode
    BAND_PASS: FilterMode
    NOTCH: FilterMode
    LOW_SHELF: FilterMode
    HIGH_SHELF: FilterMode
    PEAKING_EQ: FilterMode
    ...


class Biquad:
    def __init__(self, mode: FilterMode, frequency: BlockInput, Q: BlockInput = ..., A: BlockInput = ...) -> None:
        """Construct a biquad filter object with given settings.

        ``frequency`` gives the center frequency or corner frequency of the filter,
        depending on the mode.

        ``Q`` gives the gain or sharpness of the filter.

        ``A`` controls the gain of peaking and shelving filters according to the
        formula ``A = 10^(dBgain/40)``. For other filter types it is ignored.

        Since ``frequency`` and ``Q`` are `BlockInput` objects, they can
        be varied dynamically. Internally, this is evaluated as "direct form 1"
        biquad filter.

        The internal filter state x[] and y[] is not updated when the filter
        coefficients change, and there is no theoretical justification for why
        this should result in a stable filter output. However, in practice,
        slowly varying the filter's characteristic frequency and sharpness
        appears to work as you'd expect."""
        ...
    
    mode: FilterMode
    frequency: BlockInput
    Q: BlockInput
    A: BlockInput


class LFO:
    """A low-frequency oscillator block

    Every `rate` seconds, the output of the LFO cycles through its `waveform`.
    The output at any particular moment is ``waveform[idx] * scale + offset``.

    If `waveform` is None, a triangle waveform is used.

    `rate`, `phase_offset`, `offset`, `scale`, and `once` can be changed at
    run-time. `waveform` may be mutated.

    `waveform` must be a ``ReadableBuffer`` with elements of type ``'h'``
    (16-bit signed integer).  Internally, the elements of `waveform` are scaled
    so that the input range ``[-32768,32767]`` maps to ``[-1.0, 0.99996]``.

    An LFO only updates if it is actually associated with a playing `Synthesizer`,
    including indirectly via a `Note` or another intermediate LFO.

    Using the same LFO as an input to multiple other LFOs or Notes is OK, but
    the result if an LFO is tied to multiple `Synthesizer` objects is undefined.

    In the current implementation, LFOs are updated every 256 samples. This
    should be considered an implementation detail, though it affects how LFOs
    behave for instance when used to implement an integrator (``l.offset = l``).

    An LFO's ``value`` property is computed once when it is constructed, and then
    when its associated synthesizer updates it.

    This means that for instance an LFO **created** with ``offset=1`` has ``value==1``
    immediately, but **updating** the ``offset`` property alone does not
    change ``value``; it only updates through an association with an active synthesizer.

    The interpolation of the waveform is necessarily different depending on the
    ``once`` property. Consider a LFO with ``waveform=np.array([0, 100],
    dtype=np.int16), interpolate=True, once=True, rate=1``. Over 1 second this
    LFO's output will change from ``0`` to ``100``, and will remain at
    ``100`` thereafter, creating a "bend out" over a duration of 1 second.

    However, when ``once=False``, this creates a triangle waveform with a
    period of 1 second. Over about the first half second the input will
    increase from ``0`` to ``100``, then during the second half of the second
    it will decrease back to ``0``.

    The time of the peak output is different depending on the value of ``once``:
    At 1.0s for ``once=True`` and at 0.5s for ``once=False``.

    Because of this difference in interpolation, dynamically updating the
    ``once`` flag except when the LFO is at a phase of 0 will cause a step in
    the LFO's output.
    """
    def __init__(self, waveform: Optional[ReadableBuffer] = ..., *, rate: BlockInput = ..., scale: BlockInput = ..., offset: BlockInput = ..., phase_offset: BlockInput = ..., once: bool = ..., interpolate: bool = ...) -> None:
        ...
    
    waveform: Optional[ReadableBuffer]
    rate: BlockInput
    offset: BlockInput
    phase_offset: BlockInput
    scale: BlockInput
    once: bool
    interpolate: bool
    phase: float
    value: float
    def retrigger(self) -> None:
        """Reset the LFO's internal index to the start of the waveform. Most useful when it its `once` property is `True`."""
        ...
    


class MathOperation:
    """Operation for a Math block"""
    def __call__(self, a: BlockInput, b: BlockInput = ..., c: BlockInput = ...) -> Math:
        """A MathOperation enumeration value can be called to construct a Math block that performs that operation"""
        ...
    
    SUM: MathOperation
    ADD_SUB: MathOperation
    PRODUCT: MathOperation
    MUL_DIV: MathOperation
    SCALE_OFFSET: MathOperation
    OFFSET_SCALE: MathOperation
    LERP: MathOperation
    CONSTRAINED_LERP: MathOperation
    DIV_ADD: MathOperation
    ADD_DIV: MathOperation
    MID: MathOperation
    MAX: MathOperation
    MIN: MathOperation
    ABS: MathOperation


class Math:
    """An arithmetic block

    Performs an arithmetic operation on up to 3 inputs. See the
    documentation of ``MathOperation`` for the specific functions available.

    The properties can all be changed at run-time.

    An Math only updates if it is actually associated with a playing `Synthesizer`,
    including indirectly via a `Note` or another intermediate Math.

    Using the same Math as an input to multiple other Maths or Notes is OK, but
    the result if an Math is tied to multiple `Synthesizer` objects is undefined.

    In the current implementation, Maths are updated every 256 samples. This
    should be considered an implementation detail.
    """
    def __init__(self, operation: MathOperation, a: BlockInput, b: BlockInput = ..., c: BlockInput = ...) -> None:
        ...
    
    a: BlockInput
    b: BlockInput
    c: BlockInput
    operation: MathOperation
    value: float


class MidiTrack:
    """Simple MIDI synth"""
    def __init__(self, buffer: ReadableBuffer, tempo: int, *, sample_rate: int = ..., waveform: Optional[ReadableBuffer] = ..., envelope: Optional[Envelope] = ...) -> None:
        """Create a MidiTrack from the given stream of MIDI events. Only "Note On" and "Note Off" events
        are supported; channel numbers and key velocities are ignored. Up to two notes may be on at the
        same time.

        :param ~circuitpython_typing.ReadableBuffer buffer: Stream of MIDI events, as stored in a MIDI file track chunk
        :param int tempo: Tempo of the streamed events, in MIDI ticks per second
        :param int sample_rate: The desired playback sample rate; higher sample rate requires more memory
        :param ReadableBuffer waveform: A single-cycle waveform. Default is a 50% duty cycle square wave. If specified, must be a ReadableBuffer of type 'h' (signed 16 bit)
        :param Envelope envelope: An object that defines the loudness of a note over time. The default envelope provides no ramping, voices turn instantly on and off.

        Simple melody::

          import audioio
          import board
          import synthio

          dac = audioio.AudioOut(board.SPEAKER)
          melody = synthio.MidiTrack(b"\\0\\x90H\\0*\\x80H\\0\\6\\x90J\\0*\\x80J\\0\\6\\x90L\\0*\\x80L\\0\\6\\x90J\\0" +
                                     b"*\\x80J\\0\\6\\x90H\\0*\\x80H\\0\\6\\x90J\\0*\\x80J\\0\\6\\x90L\\0T\\x80L\\0" +
                                     b"\\x0c\\x90H\\0T\\x80H\\0\\x0c\\x90H\\0T\\x80H\\0", tempo=640)
          dac.play(melody)
          print("playing")
          while dac.playing:
            pass
          print("stopped")"""
        ...
    
    def deinit(self) -> None:
        """Deinitialises the MidiTrack and releases any hardware resources for reuse."""
        ...
    
    def __enter__(self) -> MidiTrack:
        """No-op used by Context Managers."""
        ...
    
    def __exit__(self) -> None:
        """Automatically deinitializes the hardware when exiting a context. See
        :ref:`lifetime-and-contextmanagers` for more info."""
        ...
    
    sample_rate: int
    tempo: int
    error_location: Optional[int]


class Note:
    def __init__(self, *, frequency: float, panning: BlockInput = ..., waveform: Optional[ReadableBuffer] = ..., waveform_loop_start: BlockInput = ..., waveform_loop_end: BlockInput = ..., envelope: Optional[Envelope] = ..., amplitude: BlockInput = ..., bend: BlockInput = ..., filter: Optional[Biquad] = ..., ring_frequency: float = ..., ring_bend: float = ..., ring_waveform: Optional[ReadableBuffer] = ..., ring_waveform_loop_start: BlockInput = ..., ring_waveform_loop_end: BlockInput = ...) -> None:
        """Construct a Note object, with a frequency in Hz, and optional panning, waveform, envelope, tremolo (volume change) and bend (frequency change).

        If waveform or envelope are `None` the synthesizer object's default waveform or envelope are used.

        If the same Note object is played on multiple Synthesizer objects, the result is undefined.
        """
        ...
    
    frequency: float
    filter: Optional[Biquad]
    panning: BlockInput
    amplitude: BlockInput
    bend: BlockInput
    waveform: Optional[ReadableBuffer]
    waveform_loop_start: BlockInput
    waveform_loop_end: BlockInput
    envelope: Envelope
    ring_frequency: float
    ring_bend: float
    ring_waveform: Optional[ReadableBuffer]
    ring_waveform_loop_start: BlockInput
    ring_waveform_loop_end: BlockInput


NoteSequence = Sequence[Union[int, Note]]
NoteOrNoteSequence = Union[int, Note, NoteSequence]
LFOOrLFOSequence = Union["LFO", Sequence["LFO"]]
class Synthesizer:
    def __init__(self, *, sample_rate: int = ..., channel_count: int = ..., waveform: Optional[ReadableBuffer] = ..., envelope: Optional[Envelope] = ...) -> None:
        """Create a synthesizer object.

        This API is experimental.

        Integer notes use MIDI note numbering, with 60 being C4 or Middle C,
        approximately 262Hz. Integer notes use the given waveform & envelope,
        and do not support advanced features like tremolo or vibrato.

        :param int sample_rate: The desired playback sample rate; higher sample rate requires more memory
        :param int channel_count: The number of output channels (1=mono, 2=stereo)
        :param ReadableBuffer waveform: A single-cycle waveform. Default is a 50% duty cycle square wave. If specified, must be a ReadableBuffer of type 'h' (signed 16 bit)
        :param Optional[Envelope] envelope: An object that defines the loudness of a note over time. The default envelope, `None` provides no ramping, voices turn instantly on and off.
        """
        ...
    
    def press(self, /, press: NoteOrNoteSequence = ...) -> None:
        """Turn some notes on.

        Pressing a note that was already pressed has no effect.

        :param NoteOrNoteSequence press: Any sequence of notes."""
        ...
    
    def release(self, /, release: NoteOrNoteSequence = ...) -> None:
        """Turn some notes off.

        Releasing a note that was already released has no effect.

        :param NoteOrNoteSequence release: Any sequence of notes."""
        ...
    
    def change(self, release: NoteOrNoteSequence = ..., press: NoteOrNoteSequence = ..., retrigger: LFOOrLFOSequence = ...) -> None:
        """Start notes, stop them, and/or re-trigger some LFOs.

        The changes all happen atomically with respect to output generation.

        It is OK to release note that was not actually turned on.

        Pressing a note that was already pressed returns it to the attack phase
        but without resetting its amplitude. Releasing a note and immediately
        pressing it again returns it to the attack phase with an initial
        amplitude of 0.

        At the same time, the passed LFOs (if any) are retriggered.

        :param NoteOrNoteSequence release: Any sequence of notes.
        :param NoteOrNoteSequence press: Any sequence of notes.
        :param LFOOrLFOSequence retrigger: Any sequence of LFOs.

        Note: for compatibility, ``release_then_press`` may be used as an alias
        for this function. This compatibility name will be removed in 9.0."""
        ...
    
    def release_all_then_press(self, /, press: NoteOrNoteSequence) -> None:
        """Turn any currently-playing notes off, then turn on the given notes

        Releasing a note and immediately pressing it again returns it to the
        attack phase with an initial amplitude of 0.

        :param NoteOrNoteSequence press: Any sequence of notes."""
        ...
    
    def release_all(self) -> None:
        """Turn any currently-playing notes off"""
        ...
    
    def deinit(self) -> None:
        """Deinitialises the object and releases any memory resources for reuse."""
        ...
    
    def __enter__(self) -> Synthesizer:
        """No-op used by Context Managers."""
        ...
    
    def __exit__(self) -> None:
        """Automatically deinitializes the hardware when exiting a context. See
        :ref:`lifetime-and-contextmanagers` for more info."""
        ...
    
    envelope: Optional[Envelope]
    sample_rate: int
    pressed: NoteSequence
    def note_info(self, note: Note) -> Tuple[Optional[EnvelopeState], float]:
        """Get info about a note's current envelope state

        If the note is currently playing (including in the release phase), the returned value gives the current envelope state and the current envelope value.

        If the note is not playing on this synthesizer, returns the tuple ``(None, 0.0)``.
        """
        ...
    
    blocks: List[BlockInput]


