"""
This type stub file was generated by pyright.
"""

import array
import time
from os import uname
from digitalio import DigitalInOut, Direction, Pull
from pulseio import PulseIn
from typing import Union
from microcontroller import Pin

"""
:mod:`adafruit_dhtlib`
======================

CircuitPython support for the DHT11 and DHT22 temperature and humidity devices.

* Author(s): Mike McWethy

**Hardware:**

* Adafruit `DHT22 temperature-humidity sensor + extras
  <https://www.adafruit.com/product/385>`_ (Product ID: 385)

* Adafruit `DHT11 basic temperature-humidity sensor + extras
  <https://www.adafruit.com/product/386>`_ (Product ID: 386)


**Software and Dependencies:**

* Adafruit CircuitPython firmware for the supported boards:
  https://circuitpython.org/downloads

"""
_USE_PULSEIO = ...
_USE_PULSEIO = ...
__version__ = ...
__repo__ = ...
class DHTBase:
    """base support for DHT11 and DHT22 devices

    :param bool dht11: True if device is DHT11, otherwise DHT22.
    :param ~board.Pin pin: digital pin used for communication
    :param int trig_wait: length of time to hold trigger in LOW state (microseconds)
    :param bool use_pulseio: False to force bitbang when pulseio available (only with Blinka)
    """
    __hiLevel = ...
    def __init__(self, dht11: bool, pin: Pin, trig_wait: int, use_pulseio: bool, *, max_pulses: int = ...) -> None:
        ...
    
    def exit(self) -> None:
        """Cleans up the PulseIn process. Must be called explicitly"""
        ...
    
    def measure(self) -> None:
        """measure runs the communications to the DHT11/22 type device.
        if successful, the class properties temperature and humidity will
        return the reading returned from the device.

        Raises RuntimeError exception for checksum failure and for insufficient
        data returned from the device (try again)
        """
        ...
    
    @property
    def temperature(self) -> Union[int, float, None]:
        """temperature current reading.  It makes sure a reading is available

        Raises RuntimeError exception for checksum failure and for insufficient
        data returned from the device (try again)
        """
        ...
    
    @property
    def humidity(self) -> Union[int, float, None]:
        """humidity current reading. It makes sure a reading is available

        Raises RuntimeError exception for checksum failure and for insufficient
        data returned from the device (try again)
        """
        ...
    


class DHT11(DHTBase):
    """Support for DHT11 device.

    :param ~board.Pin pin: digital pin used for communication
    """
    def __init__(self, pin: Pin, use_pulseio: bool = ...) -> None:
        ...
    


class DHT22(DHTBase):
    """Support for DHT22 device.

    :param ~board.Pin pin: digital pin used for communication
    """
    def __init__(self, pin: Pin, use_pulseio: bool = ...) -> None:
        ...
    


class DHT21(DHTBase):
    """Support for DHT21/AM2301 device.

    :param ~board.Pin pin: digital pin used for communication
    """
    def __init__(self, pin: Pin, use_pulseio: bool = ...) -> None:
        ...
    


