# Documentation: https://doc.traefik.io/traefik/reference/install-configuration/configuration-options/

ping:
  entryPoint: traefik

api:
  dashboard: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"

certificatesResolvers:
  porkbun-api:
    acme:
      email: info@growzone.tech
      storage: /etc/traefik-certs/acme.json
      dnschallenge:
        provider: porkbun
        propagation:
          delaybeforechecks: 60

providers:
  file:
    directory: "/etc/traefik/dynamic"