"""
This type stub file was generated by pyright.
"""

import digitalio
import microcontroller
from typing import Optional, Protocol

"""Basic digital pin support

The `digitalio` module contains classes to provide access to basic digital IO.

All classes change hardware state and should be deinitialized when they
are no longer needed if the program continues after use. To do so, either
call :py:meth:`!deinit` or use a context manager. See
:ref:`lifetime-and-contextmanagers` for more info.

For example::

  import digitalio
  import board

  pin = digitalio.DigitalInOut(board.LED)
  print(pin.value)

This example will initialize the the device, read
:py:data:`~digitalio.DigitalInOut.value` and then
:py:meth:`~digitalio.DigitalInOut.deinit` the hardware.

Here is blinky::

  import time
  import digitalio
  import board

  led = digitalio.DigitalInOut(board.LED)
  led.direction = digitalio.Direction.OUTPUT
  while True:
      led.value = True
      time.sleep(0.1)
      led.value = False
      time.sleep(0.1)

For the essentials of `digitalio`, see the `CircuitPython Essentials
Learn guide <https://learn.adafruit.com/circuitpython-essentials/circuitpython-digital-in-out>`_

For more information on using `digitalio`, see `this additional Learn guide
<https://learn.adafruit.com/circuitpython-digital-inputs-and-outputs>`_

.. warning:: `digitalio.DigitalInOut` on Raspberry Pi RP2350 A2 stepping has some limitations
   due to a GPIO hardware issue that causes excessive leakage current (~120uA).
   A pin can read as high even when driven or pulled low, if the input signal is high
   impedance or if an attached pull-down resistor is too weak (has too high a value).

   To prevent this problem, drive the the input pin with a strong signal that can overcome
   the leakage current. If you need to use a pull-down,
   connect a strong external pull-down resistor that is 8.2k ohms or less.

   The internal pull-down resistor (``digitalio.DigitalInOut.pull = digitalio.Pull.DOWN``)
   is not strong enough, and is not useful.

   Typical push-pull outputs from attached peripherals or other microcontrollers will drive
   input pins adequately, with no resistor needed.

   There is no problem when pull-ups are used, even weak ones. Using the internal pull-up resistor
   (``digitalioDigitalInOut.pull = digitalio.Pull.UP``) will work fine.

   For more information, see the RP2350-E9 erratum in the
   `RP2350 datasheet <https://datasheets.raspberrypi.com/rp2350/rp2350-datasheet.pdf>`_
"""
class DriveMode:
    """Defines the drive mode of a digital pin"""
    def __init__(self) -> None:
        """Enum-like class to define the drive mode used when outputting
        digital values."""
        ...
    
    PUSH_PULL: DriveMode
    OPEN_DRAIN: DriveMode


class DigitalInOut:
    """Digital input and output

    A DigitalInOut is used to digitally control I/O pins. For analog control of
    a pin, see the :py:class:`analogio.AnalogIn` and
    :py:class:`analogio.AnalogOut` classes."""
    def __init__(self, pin: microcontroller.Pin) -> None:
        """Create a new DigitalInOut object associated with the pin. Defaults to input
        with no pull. Use :py:meth:`switch_to_input` and
        :py:meth:`switch_to_output` to change the direction.

        :param ~microcontroller.Pin pin: The pin to control"""
        ...
    
    def deinit(self) -> None:
        """Turn off the DigitalInOut and release the pin for other use."""
        ...
    
    def __enter__(self) -> DigitalInOut:
        """No-op used by Context Managers."""
        ...
    
    def __exit__(self) -> None:
        """Automatically deinitializes the hardware when exiting a context. See
        :ref:`lifetime-and-contextmanagers` for more info."""
        ...
    
    def switch_to_output(self, value: bool = ..., drive_mode: DriveMode = ...) -> None:
        """Set the drive mode and value and then switch to writing out digital
        values.

        :param bool value: default value to set upon switching
        :param ~digitalio.DriveMode drive_mode: drive mode for the output
        """
        ...
    
    def switch_to_input(self, pull: Optional[Pull] = ...) -> None:
        """Set the pull and then switch to read in digital values.

        :param Pull pull: pull configuration for the input

        Example usage::

          import digitalio
          import board

          switch = digitalio.DigitalInOut(board.SLIDE_SWITCH)
          switch.switch_to_input(pull=digitalio.Pull.UP)
          # Or, after switch_to_input
          switch.pull = digitalio.Pull.UP
          print(switch.value)"""
        ...
    
    direction: Direction
    value: bool
    drive_mode: DriveMode
    pull: Optional[Pull]


class DigitalInOutProtocol(Protocol):
    """Protocol for digital input/output pin control.

    Any object that implements this protocol can be used as a digital pin,
    providing compatibility with code expecting a `digitalio.DigitalInOut`.
    """
    def deinit(self) -> None:
        """Deinitialize the pin and release hardware resources."""
        ...
    
    def deinited(self) -> bool:
        """Check whether the pin has been deinitialized.

        :return: True if deinitialized, False otherwise
        """
        ...
    
    def switch_to_input(self, pull: Optional[digitalio.Pull] = ...) -> None:
        """Configure the pin as a digital input.

        :param pull: Pull resistor configuration (UP, DOWN, or None)
        """
        ...
    
    def switch_to_output(self, value: bool = ..., drive_mode: digitalio.DriveMode = ...) -> None:
        """Configure the pin as a digital output.

        :param value: Initial output value (default False)
        :param drive_mode: Output drive mode (PUSH_PULL or OPEN_DRAIN)
        """
        ...
    
    @property
    def direction(self) -> digitalio.Direction:
        """The pin direction (INPUT or OUTPUT)."""
        ...
    
    @direction.setter
    def direction(self, value: digitalio.Direction) -> None:
        ...
    
    @property
    def value(self) -> bool:
        """The digital logic level of the pin."""
        ...
    
    @value.setter
    def value(self, val: bool) -> None:
        ...
    
    @property
    def pull(self) -> Optional[digitalio.Pull]:
        """The pull resistor configuration for inputs (UP, DOWN, or None)."""
        ...
    
    @pull.setter
    def pull(self, pul: Optional[digitalio.Pull]) -> None:
        ...
    
    @property
    def drive_mode(self) -> digitalio.DriveMode:
        """The drive mode for outputs (PUSH_PULL or OPEN_DRAIN)."""
        ...
    
    @drive_mode.setter
    def drive_mode(self, mode: digitalio.DriveMode) -> None:
        ...
    


class Direction:
    """Defines the direction of a digital pin"""
    def __init__(self) -> None:
        """Enum-like class to define which direction the digital values are
        going."""
        ...
    
    INPUT: Direction
    OUTPUT: Direction


class Pull:
    """Defines the pull of a digital input pin"""
    def __init__(self) -> None:
        """Enum-like class to define the pull value, if any, used while reading
        digital values in."""
        ...
    
    UP: Pull
    DOWN: Pull


