"""
This type stub file was generated by pyright.
"""

from datetime import timedelta
from select import select
from typing import Optional, TYPE_CHECKING, Union
from collections.abc import Generator, Iterable
from .line_settings import LineSettings

if TYPE_CHECKING:
    ...
__all__ = ["poll_fd", "config_iter"]
def poll_fd(fd: int, timeout: Optional[Union[timedelta, float]] = ...) -> bool:
    ...

def config_iter(config: dict[Union[Iterable[Union[int, str]], int, str], Optional[LineSettings]]) -> Generator[tuple[Union[int, str], Optional[LineSettings]]]:
    ...

