"""
This type stub file was generated by pyright.
"""

import array
import alarm
import audiocore
import audiomixer
import audiomp3
import rgbmatrix
import synthio
import ulab
from typing import Optional, TYPE_CHECKING, Union
from typing_extensions import Protocol, TypeAlias
from alarm.pin import PinAlarm
from alarm.time import TimeAlarm
from ulab.numpy import ndarray

"""
`circuitpython_typing`
================================================================================

Types needed for type annotation that are not in `typing`


* Author(s): Alec Delaney, Dan Halbert, Randy Hudson
"""
__version__ = ...
__repo__ = ...
if TYPE_CHECKING:
    ...
__all__ = ["Alarm", "AudioSample", "BlockDevice", "ByteStream", "FrameBuffer", "ReadableBuffer", "WriteableBuffer"]
ReadableBuffer: TypeAlias = Union[array.array, bytearray, bytes, memoryview, "rgbmatrix.RGBMatrix", "ulab.numpy.ndarray",]
WriteableBuffer: TypeAlias = Union[array.array, bytearray, memoryview, "rgbmatrix.RGBMatrix", "ulab.numpy.ndarray",]
class ByteStream(Protocol):
    """Protocol for basic I/O operations on a byte stream.
    Classes which implement this protocol include
    * `io.BytesIO`
    * `io.FileIO` (for a file open in binary mode)
    * `busio.UART`
    * `usb_cdc.Serial`
    """
    def read(self, count: Optional[int] = ..., /) -> Optional[bytes]:
        """Read ``count`` bytes from the stream.
        If ``count`` bytes are not immediately available,
        or if the parameter is not specified in the call,
        the outcome is implementation-dependent.
        """
        ...
    
    def write(self, buf: ReadableBuffer, /) -> Optional[int]:
        """Write the bytes in ``buf`` to the stream."""
        ...
    


class BlockDevice(Protocol):
    """Protocol for block device objects to enable a device to support
    CircuitPython filesystems. Classes which implement this protocol
    include `storage.VfsFat`.
    """
    def readblocks(self, start_block: int, buf: WriteableBuffer) -> None:
        """Read aligned, multiples of blocks. Starting at
        the block given by the index ``start_block``, read blocks
        from the device into ``buf``. The number of blocks to
        read is given by the length of ``buf``, which will be a
        multiple of the block size.
        """
        ...
    
    def writeblocks(self, start_block: int, buf: ReadableBuffer) -> None:
        """Write aligned, multiples of blocks, and require that
        the blocks that are written to be first erased (if necessary)
        by this method. Starting at the block given by the index
        ``start_block``, write blocks from ``buf`` to the device.
        The number of blocks to write is given by the length
        of ``buf``, which will be a multiple of the block size.
        """
        ...
    


AudioSample: TypeAlias = Union["audiocore.WaveFile", "audiocore.RawSample", "audiomixer.Mixer", "audiomp3.MP3Decoder", "synthio.MidiTrack",]
FrameBuffer: TypeAlias = Union["rgbmatrix.RGBMatrix"]
Alarm: TypeAlias = Union["alarm.pin.PinAlarm", "alarm.time.TimeAlarm"]
