{
 "title": "Hardware Metrics",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "mainDisk",
    "label": "Main Disk",
    "query": {
     "query": "SELECT DISTINCT \"device\" FROM \"disk\""
    }
   },
   {
    "name": "interval",
    "label": "Window Size",
    "query": "Auto : NULL, 15s : '15 seconds', 30s : '30 seconds', 1m : '1 minutes', 5m : '5 minutes', 10m : '10 minutes', 30m : '30 minutes', 1h : '1 hours'"
   }
  ]
 },
 "panels": [
  { "title": "Host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT\n  \"time_bin\" AS \"time\",\n  \"core_id\",\n  \"usage\"\nFROM\n  (\n    SELECT\n      date_bin(COALESCE($interval,'$__interval_ms milliseconds')::INTERVAL, \"time\") AS \"time_bin\",\n      \"core_id\",\n      AVG(\"usage_user\" + \"usage_system\") AS \"usage\"\n    FROM\n      \"cpu\"\n    WHERE\n      \"time\" >= $__timeFrom\n      AND \"time\" <= $__timeTo\n    GROUP BY\n      \"core_id\",\n      \"time_bin\"\n  )\nORDER BY\n  \"time\" ASC"
    }
   ]
  },
  {
   "title": "Disk Space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT\n  \"time_bin\" AS \"time\",\n  \"usage\",\n  \"total\"\nFROM\n  (\n    SELECT\n      date_bin(COALESCE($interval,'$__interval_ms milliseconds')::INTERVAL, \"time\") AS \"time_bin\",\n      AVG(\"used\") AS \"usage\",\n      AVG(\"total\") AS \"total\"\n    FROM\n      \"disk\"\n    WHERE\n      \"time\" >= $__timeFrom\n      AND \"time\" <= $__timeTo\n    GROUP BY\n      \"time_bin\"\n  )\nORDER BY\n  \"time\" ASC"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT\n  \"time_bin\" AS \"time\",\n  \"usage\",\n  \"total\"\nFROM\n  (\n    SELECT\n      date_bin(COALESCE($interval,'$__interval_ms milliseconds')::INTERVAL, \"time\") AS \"time_bin\",\n      AVG(\"used\") AS \"usage\",\n      AVG(\"total\") AS \"total\"\n    FROM\n      \"mem\"\n    WHERE\n      \"time\" >= $__timeFrom\n      AND \"time\" <= $__timeTo\n    GROUP BY\n      \"time_bin\"\n  )\nORDER BY\n  \"time\" ASC"
    }
   ]
  },
  {
   "title": "Swap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT\n  \"time_bin\" AS \"time\",\n  \"free\",\n  \"total\"\nFROM\n  (\n    SELECT\n      date_bin(COALESCE($interval,'$__interval_ms milliseconds')::INTERVAL, \"time\") AS \"time_bin\",\n      AVG(\"swap_free\") AS \"free\",\n      AVG(\"swap_total\") AS \"total\"\n    FROM\n      \"mem\"\n    WHERE\n      \"time\" >= $__timeFrom\n      AND \"time\" <= $__timeTo\n    GROUP BY\n      \"time_bin\"\n  )\nORDER BY\n  \"time\" ASC"
    }
   ]
  },
  { "title": "Docker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Container Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT\n  \"time\",\n  CASE WHEN \"created\" = 0 THEN NULL ELSE \"created\" END AS \"created\",\n  CASE WHEN \"restarting\" = 0 THEN NULL ELSE \"restarting\" END AS \"restarting\",\n  CASE WHEN \"running_healthy\" = 0 THEN NULL ELSE \"running_healthy\" END AS \"running_healthy\",\n  CASE WHEN \"running_unhealthy\" = 0 THEN NULL ELSE \"running_unhealthy\" END AS \"running_unhealthy\",\n  CASE WHEN \"removing\" = 0 THEN NULL ELSE \"removing\" END AS \"removing\",\n  CASE WHEN \"paused\" = 0 THEN NULL ELSE \"paused\" END AS \"paused\",\n  CASE WHEN \"exited\" = 0 THEN NULL ELSE \"exited\" END AS \"exited\",\n  CASE WHEN \"dead\" = 0 THEN NULL ELSE \"dead\" END AS \"dead\",\n  CASE WHEN \"unknown_status\" = 0 THEN NULL ELSE \"unknown_status\" END AS \"unknown_status\",\n  CASE WHEN \"total_health\" = 0 THEN NULL ELSE \"total_health\" END AS \"total_health\"\nFROM\n  (\n    SELECT\n      \"time_bin\" AS \"time\",\n      SUM(\"created\") AS \"created\",\n      SUM(\"restarting\") AS \"restarting\",\n      SUM(\"running_healthy\") AS \"running_healthy\",\n      SUM(\"running_unhealthy\") AS \"running_unhealthy\",\n      SUM(\"removing\") AS \"removing\",\n      SUM(\"paused\") AS \"paused\",\n      SUM(\"exited\") AS \"exited\",\n      SUM(\"dead\") AS \"dead\",\n      SUM(\"unknown_status\") AS \"unknown_status\",\n      SUM(\"created\" + \"restarting\" + \"running_healthy\" + \"running_unhealthy\" + \"removing\" + \"paused\" + \"exited\" + \"dead\") AS \"total_health\"\n    FROM\n      (\n        SELECT\n          date_bin(COALESCE($interval,'$__interval_ms milliseconds')::INTERVAL, \"time\") AS \"time_bin\",\n          `com.docker.compose.service` AS \"service\",\n          AVG(CASE WHEN \"container_status\" = 'created' THEN 1.0 ELSE 0.0 END) AS \"created\",\n          AVG(CASE WHEN \"container_status\" = 'restarting' THEN 1.0 ELSE 0.0 END) AS \"restarting\",\n          AVG(CASE WHEN \"container_status\" = 'running' AND \"health_status\" = 'healthy' THEN 1.0 ELSE 0.0 END) AS \"running_healthy\",\n          AVG(CASE WHEN \"container_status\" = 'running' AND \"health_status\" != 'healthy' THEN 1.0 ELSE 0.0 END) AS \"running_unhealthy\",\n          AVG(CASE WHEN \"container_status\" = 'removing' THEN 1.0 ELSE 0.0 END) AS \"removing\",\n          AVG(CASE WHEN \"container_status\" = 'paused' THEN 1.0 ELSE 0.0 END) AS \"paused\",\n          AVG(CASE WHEN \"container_status\" = 'exited' THEN 1.0 ELSE 0.0 END) AS \"exited\",\n          AVG(CASE WHEN \"container_status\" = 'dead' THEN 1.0 ELSE 0.0 END) AS \"dead\",\n          AVG(CASE WHEN \"container_status\" NOT IN ('created', 'restarting', 'running', 'removing', 'paused', 'exited', 'dead') THEN 1.0 ELSE 0.0 END) AS \"unknown_status\"\n        FROM\n          \"docker_container_health\"\n        WHERE\n          \"time\" >= $__timeFrom\n          AND \"time\" <= $__timeTo\n        GROUP BY\n          \"service\",\n          \"time_bin\"\n      )\n    GROUP BY\n      \"time\"\n  )\nORDER BY\n  \"time\" ASC"
    },
    {
     "dataset": "iox",
     "rawSql": "SELECT\n  \"time_bin\" AS \"time\",\n  \"total_containers\"\nFROM\n  (\n    SELECT\n      date_bin(COALESCE($interval,'$__interval_ms milliseconds')::INTERVAL, \"time\") AS \"time_bin\",\n      AVG(\"n_containers\") AS \"total_containers\",\n    FROM\n      \"docker\"\n    WHERE\n      \"time\" >= $__timeFrom\n      AND \"time\" <= $__timeTo\n    GROUP BY\n      \"time_bin\"\n  )\nORDER BY\n  \"time\" ASC"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT `com.docker.compose.service` AS \"Service\", selector_last(\"container_status\", \"time\")['value'] AS \"Status\", selector_last(\"health_status\", \"time\")['value'] AS \"Health\" FROM \"docker_container_health\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo GROUP BY \"Service\" ORDER BY \"Service\" ASC"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT\n  \"time_bin\" AS \"time\",\n  \"service\",\n  \"usage\"\nFROM\n  (\n    SELECT\n      date_bin(COALESCE($interval,'$__interval_ms milliseconds')::INTERVAL, \"time\") AS \"time_bin\",\n      `com.docker.compose.service` AS \"service\",\n      AVG(\"usage_percent\") AS \"usage\"\n    FROM\n      \"docker_container_cpu\"\n    WHERE\n      \"time\" >= $__timeFrom\n      AND \"time\" <= $__timeTo\n    GROUP BY\n      \"service\",\n      \"time_bin\"\n  )\nORDER BY\n  \"time\" ASC"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT\n  \"time_bin\" AS \"time\",\n  \"service\",\n  \"usage\"\nFROM\n  (\n    SELECT\n      date_bin(COALESCE($interval,'$__interval_ms milliseconds')::INTERVAL, \"time\") AS \"time_bin\",\n      `com.docker.compose.service` AS \"service\",\n      AVG(\"usage\") AS \"usage\"\n    FROM\n      \"docker_container_mem\"\n    WHERE\n      \"time\" >= $__timeFrom\n      AND \"time\" <= $__timeTo\n    GROUP BY\n      \"service\",\n      \"time_bin\"\n  )\nORDER BY\n  \"time\" ASC"
    }
   ]
  }
 ]
}