[[inputs.mqtt_consumer]] # https://docs.influxdata.com/telegraf/v1/input-plugins/mqtt_consumer/
  servers = ["tcp://${APP_NAME_HOST}_mosquitto:1883"]
  topics = [
    "v1/sensors/+/+/+", # Ex.: v1/sensors/dht22/inside/temperature
  ]
  data_format = "value"
  data_type = "float"
  [[inputs.mqtt_consumer.topic_parsing]]
    topic = "v1/sensors/+/+/+"
    measurement = "_/_/_/_/measurement"
    tags = "_/_/sensor-type/location/_"
    # fields = "_/_/_/_/_"
  [inputs.mqtt_consumer.tags]
    __influxdb__database = "sensor-data"

[[inputs.mqtt_consumer]] # https://docs.influxdata.com/telegraf/v1/input-plugins/mqtt_consumer/
  servers = ["tcp://${APP_NAME_HOST}_mosquitto:1883"]
  topics = [
    "v1/get/actors/+/+/+", # Ex.: v1/sensors/dht22/inside/temperature
  ]
  data_format = "value"
  data_type = "float"
  [[inputs.mqtt_consumer.topic_parsing]]
    topic = "v1/get/actors/+/+/+"
    measurement = "_/_/_/_/_/measurement"
    tags = "_/_/_/sensor-type/location/_"
    # fields = "_/_/_/_/_/_"
  [inputs.mqtt_consumer.tags]
    __influxdb__database = "sensor-data"