# Documentation: https://github.com/glanceapp/glance/blob/main/docs/configuration.md
# si-prefix icons: https://simpleicons.org/ (externally loaded!)
# di-prefix icons: https://github.com/homarr-labs/dashboard-icons/blob/main/ICONS.md
server:
  assets-path: /app/assets
  proxied: true
branding:
  custom-footer: |
    <p>Copyright (c) <a href="https://github.com/growzone-tech/growzone">${APP_OWNER}</a></p>
    <p>Powered by <a href="https://github.com/glanceapp/glance">Glance</a></p>
  app-name: ${APP_NAME_LABEL}
  # logo-url: /assets/logo/logo.svg
  # favicon-url: /assets/logo/favicon.svg
  # app-icon-url: /assets/logo/app-icon.svg
theme:
  background-color: 50 1 6
  # primary-color: 24 97 58
  # negative-color: 209 88 54
  # primary-color: 51 33 68
  contrast-multiplier: 1.2
  primary-color: 217 92 83
  positive-color: 115 54 76
  negative-color: 347 70 65
pages:
  - name: Apps
    slug: apps
    center-vertically: true
    columns:
      - size: full
        widgets:
          - type: split-column
            max-columns: 3
            widgets:
              - type: monitor
                cache: 10s
                sites:
                  - title: Grafana
                    url: https://grafana.${APP_HOST}
                    check-url: https://grafana.${APP_HOST}
                    icon: /assets/icons/si/grafana.svg
                  - title: "MQTTX"
                    url: https://mqttx.${APP_HOST}
                    check-url: https://mqttx.${APP_HOST}
                    icon: /assets/icons/si/mqtt.svg
                  - title: "Traefik Dashboard"
                    url: https://traefik.${APP_HOST}
                    check-url: https://traefik.${APP_HOST}
                    icon: /assets/icons/si/traefik-proxy.svg
              - type: monitor
                cache: 10s
                sites:
                  - title: LLDAP
                    url: https://lldap.${APP_HOST}
                    check-url: http://lldap.${APP_HOST}
                    icon: /assets/icons/si/lldap-dark.svg
  #     - size: small
  #       widgets:
  #         - type: monitor
  #           define: &sp
  #             url: "#"
  #             same-tab: true
  #             icon: /assets/icons/si/docker.svg
  #           cache: 10s
  #           title: Service Health
  #           style: compact
  #           sites:
  #             - title: Ollama
  #               <<: *sp
  #               check-url: http://ollama:11434
  #               icon: /assets/icons/si/ollama.svg
  #             - title: Tailscale
  #               <<: *sp
  #               check-url: http://127.0.0.1:8080
  #               icon: /assets/icons/si/tailscale.svg
  #             - title: Speaches
  #               <<: *sp
  #               check-url: http://speaches:8000/health
  #               alt-status-codes:
  #                 - 403
  #               icon: /assets/icons/si/audiomack.svg
  - name: Development
    slug: dev
    columns:
      - size: small
        widgets:
          - type: releases
            cache: 1d # Also see: https://github.com/glanceapp/glance/blob/main/docs/configuration.md#token
            show-source-icon: true
            repositories:
              - growzone-tech/growzone
              - dockerhub:traefik:latest
              - dockerhub:tailscale/tailscale:stable
              - dockerhub:eclipse-mosquitto:latest
              - dockerhub:emqx/mqttx-web:latest
              - dockerhub:grafana/grafana:latest
              - dockerhub:authelia/authelia:latest
              - dockerhub:lldap/lldap:stable
              - dockerhub:influxdb:3-core
              - dockerhub:telegraf:latest
              - tecnativa/docker-socket-proxy
              - dockerhub:glanceapp/glance:latest

      - size: full
        widgets:
          - type: iframe
            source: 'https://grafana.otto420.growzone.tech/d-solo/hardware-metrics/hardware-metrics?orgId=1&from=now-24h&to=now&timezone=browser&var-mainDisk=&var-interval=NULL&refresh=1m&panelId=panel-8&__feature.dashboardScene=true'
            height: 200


      - size: small
        widgets:
          - type: weather
            location: Aachen, Germany
            units: metric
            hour-format: 24h
            hide-location: true